services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"   
    container_name: sentinel-postgres

    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_dev
  

    volumes:
      - sentinel-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d sentinel"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: sentinel-backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sentinel
      SPRING_DATASOURCE_USERNAME: sentinel
      SPRING_DATASOURCE_PASSWORD: sentinel_dev

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  sentinel-postgres-data: