spring.application.name=sentinel-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel
spring.datasource.username=sentinel
spring.datasource.password=sentinel_dev

spring.jpa.hibernate.ddl-auto=update