spring.application.name=sentinel-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel
spring.datasource.username=sentinel
spring.datasource.password=sentinel_dev

spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=Sentinel
info.app.description=Security event monitoring backend
info.app.version=1.0.0