--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analyst; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analyst (
    id bigint NOT NULL,
    password_hash character varying(255),
    username character varying(255),
    role character varying(255) DEFAULT 'ANALYST'::character varying NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT analyst_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'ANALYST'::character varying])::text[])))
);


--
-- Name: analyst_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analyst ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyst_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investigation_case; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investigation_case (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    security_event_id bigint NOT NULL,
    CONSTRAINT investigation_case_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: investigation_case_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.investigation_case ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investigation_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: security_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.security_event (
    id bigint NOT NULL,
    event_type character varying(255) NOT NULL,
    ip_address character varying(255),
    message character varying(255) NOT NULL,
    severity character varying(255) NOT NULL,
    source character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) with time zone NOT NULL,
    CONSTRAINT security_event_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['FAILED_LOGIN'::character varying, 'PORT_SCAN'::character varying, 'MALWARE_DETECTED'::character varying, 'SUSPICIOUS_REQUEST'::character varying])::text[]))),
    CONSTRAINT security_event_severity_check CHECK (((severity)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT security_event_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'REVIEWED'::character varying, 'ESCALATED'::character varying])::text[])))
);


--
-- Name: security_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.security_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.security_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analyst analyst_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analyst
    ADD CONSTRAINT analyst_pkey PRIMARY KEY (id);


--
-- Name: investigation_case investigation_case_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_case
    ADD CONSTRAINT investigation_case_pkey PRIMARY KEY (id);


--
-- Name: security_event security_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_event
    ADD CONSTRAINT security_event_pkey PRIMARY KEY (id);


--
-- Name: investigation_case uk650b1qovbl0ubhqajfxi4lc8g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_case
    ADD CONSTRAINT uk650b1qovbl0ubhqajfxi4lc8g UNIQUE (security_event_id);


--
-- Name: investigation_case fkge92eju3362h3mobcsqi1c23m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_case
    ADD CONSTRAINT fkge92eju3362h3mobcsqi1c23m FOREIGN KEY (security_event_id) REFERENCES public.security_event(id);


--
-- PostgreSQL database dump complete
--


